name: checkout-credentials

on:
  pull_request_target:
  push:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  audit-pr:
    if: github.event_name == 'pull_request_target'
    uses: florianhorner/gh-workflows/.github/workflows/checkout-credentials.yml@fde64f42deb15511c2c71cb9798c2d6685379e38 # checkout-credentials v1.1
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  audit-push:
    if: github.event_name == 'push'
    uses: florianhorner/gh-workflows/.github/workflows/checkout-credentials.yml@fde64f42deb15511c2c71cb9798c2d6685379e38 # checkout-credentials v1.1
